- name: Hello World Sample
  hosts: all
  tasks:
    - name: copy script
      copy: src=test.sh dest=/home/support mode=0777
    - name: run shell
      command: sh /home/support/mysql-create.sh {{mysql_root_password}} {{dbname}}
      register: command_output
    - debug:
         var: command_output.stdout_lines